#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine

sudo apt purge -y nginx nginx-common
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/new_404.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sudo sed -i '/server_name _/a error_page 404 /new_404.html; \nlocation = /new_404.html \n{\nroot /var/www/html/;\ninternal;\n}\nadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart

